name: CI/CD Release Workflow

on:
  push:
    branches: [main]

  release:
    types: [published]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cache Conda
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache if deploy/conda-dev-spec.template has not changed in the workflow
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('dev-environment.txt') }}

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: "mosaic_ci"
          miniforge-version: latest
          channels: conda-forge,e3sm/label/mosaic,defaults
          channel-priority: strict
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Install mosaic
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          conda create -n mosaic_dev --file dev-environment.txt \
            python=${{ matrix.python-version }}
          conda activate mosaic_dev
          python -m pip install -e .

      - name: Build Sphinx Docs
        run: |
          set -e
          conda activate mosaic_dev
          pip check
          cd docs
          make html
      - name: Copy Docs and Commit
        run: |
          set -e
          conda activate mosaic_dev
          pip check
          cd docs
          # gh-pages branch must already exist
          git clone https://github.com/E3SM-Project/mosaic.git --branch gh-pages --single-branch gh-pages
          # Make sure we're in the gh-pages directory.
          cd gh-pages
          # Create `.nojekyll` (if it doesn't already exist) for proper GH Pages configuration.
          touch .nojekyll
          # Only replace `main` docs with latest changes. Docs for releases should be untouched.
          rm -rf *
          # copy source files, clobbering any existing (i.e. no `-n`)
          cp -r ../_build/html/* .
          # Configure git using GitHub Actions credentials.
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # The second command will fail if no changes were present, so we ignore it
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: docs/gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
